In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:

jobs = pd.read_csv("postings.csv")
skills = pd.read_csv("jobs/job_skills.csv")
salary = pd.read_csv("jobs/salaries.csv")
companies = pd.read_csv("companies/companies.csv")

In [3]:
jobs.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [4]:
jobs.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   str
 6   location                    123849 non-null  str
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  str
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  str
 16  application_url             87184 non-null   str
 17  application_type            123849 non-null  str
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   str
 21  skills_desc                 2439 non-null    str
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   str
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  str
 26  currency                    36073 non-null   str
 27  compensation_type           36073 non-null   str
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), str(15)
memory usage: 508.5 MB

In [5]:

jobs.columns

Index(['job_id', 'company_name', 'title', 'description', 'max_salary',
       'pay_period', 'location', 'company_id', 'views', 'med_salary',
       'min_salary', 'formatted_work_type', 'applies', 'original_listed_time',
       'remote_allowed', 'job_posting_url', 'application_url',
       'application_type', 'expiry', 'closed_time',
       'formatted_experience_level', 'skills_desc', 'listed_time',
       'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type', 'normalized_salary', 'zip_code', 'fips'],
      dtype='str')

In [6]:
jobs.drop_duplicates(inplace=True)

In [7]:
jobs.isnull().sum()

job_id                             0
company_name                    1719
title                              0
description                        7
max_salary                     94056
pay_period                     87776
location                           0
company_id                      1717
views                           1689
med_salary                    117569
min_salary                     94056
formatted_work_type                0
applies                       100529
original_listed_time               0
remote_allowed                108603
job_posting_url                    0
application_url                36665
application_type                   0
expiry                             0
closed_time                   122776
formatted_experience_level     29409
skills_desc                   121410
listed_time                        0
posting_domain                 39968
sponsored                          0
work_type                          0
currency                       87776
compensation_type              87776
normalized_salary              87776
zip_code                       20872
fips                           27415
dtype: int64

In [8]:
jobs = jobs.drop(columns=[
    'max_salary',
    'min_salary',
    'med_salary',
    'skills_desc',
    'closed_time',
    'compensation_type',
    'normalized_salary'
])

In [9]:
jobs.shape

(123849, 24)

In [10]:
top_company = jobs['company_id'].value_counts().head(10)
print(top_company)

company_id
53345529.0    1108
167757.0      1003
73013724.0     604
2152.0         529
4128.0         527
3175.0         517
1419.0         496
163139.0       476
11056.0        418
6849.0         415
Name: count, dtype: int64

In [11]:
jobs['location'].value_counts().head(10)

location
United States    8125
New York, NY     2756
Chicago, IL      1834
Houston, TX      1762
Dallas, TX       1383
Atlanta, GA      1363
Boston, MA       1176
Austin, TX       1083
Charlotte, NC    1075
Phoenix, AZ      1059
Name: count, dtype: int64

In [12]:
skills.head()

       job_id skill_abr
0  3884428798      MRKT
1  3884428798        PR
2  3884428798       WRT
3  3887473071      SALE
4  3887465684       FIN

In [13]:
top_skills = skills['skill_abr'].value_counts().head(20)
print(top_skills)

skill_abr
IT      26137
SALE    22475
MGMT    20861
MNFC    18185
HCPR    17369
BD      14290
ENG     13009
OTHR    12608
FIN      8540
MRKT     5525
ACCT     5461
ADM      4860
CUST     4292
PRJM     3997
ANLS     3858
RSCH     2986
HR       2647
LGL      2371
CNSL     2338
EDU      2290
Name: count, dtype: int64

In [14]:
salary.describe()

          salary_id        job_id    max_salary     med_salary    min_salary
count  40785.000000  4.078500e+04  3.394700e+04    6838.000000  3.394700e+04
mean   20393.000000  3.895564e+09  9.620987e+04   21370.298197  6.508541e+04
std    11773.759701  9.496672e+07  6.587373e+05   51338.564166  4.650612e+05
min        1.000000  9.217160e+05  1.000000e+00       0.000000  1.000000e+00
25%    10197.000000  3.894608e+09  5.000000e+01      18.500000  3.900000e+01
50%    20393.000000  3.901980e+09  8.500000e+04      25.000000  6.230000e+04
75%    30589.000000  3.904576e+09  1.425000e+05    2207.000000  1.000000e+05
max    40785.000000  3.906267e+09  1.200000e+08  750000.000000  8.500000e+07

In [15]:
max_Sal = salary['max_salary'].mean()
print(max_Sal)

96209.87183432998

In [17]:
jobs.to_csv("postings_final.csv", index=False)
skills.to_csv("job_skills_final.csv", index=False)
salary.to_csv("salaries_final.csv", index=False)
print("Save")

Save